### ISSUE TITLE
cell selection does not work

### ISSUE THREAD

**Issue by RiegebMic** [hoogi91/spreadsheets#13]
**Version(s) affected**: spreadsheets_1.1.1

**Description**  
Somehow the cell selection function isn't working. I don't know why, maybe you can help me there.
I need the function for an important school project.

Maybe it has something to do with this error typo3 shows me:
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Class 'Hoogi91\Spreadsheets\Utility\ExtensionManagementUtility' not found | Error thrown in file C:\xampp\htdocs\typo3\typo3conf\ext\spreadsheets\Configuration\TCA\Overrides\tt_content.php in line 6. Requested URL: http://localhost/typo3/typo3/index.php?route=%%2Ftools%%2FExtensionmanagerExtensionmanager%%2F&token=--AnonymizedToken--

Typo3 cell selection:
![spreadsheet_selection](https://user-images.githubusercontent.com/59868086/72333600-58d00200-36bc-11ea-9008-ce3c47611d69.PNG)

Output:
![view](https://user-images.githubusercontent.com/59868086/72333601-58d00200-36bc-11ea-83ff-e29d22c45b3e.PNG)

tt_content.php config
![tt_content](https://user-images.githubusercontent.com/59868086/72334574-d0526100-36bd-11ea-9748-eb937e67c0db.PNG)

**Comment by hoogi91** [comment]
Hey @RiegebMic,

thanks for your report. You are right that the current implementation of `Hoogi91\Spreadsheets\DataProcessing\SpreadsheetProcessor` is not able to render only the selected cells if the default "Spreadsheet Table" element is extended as described in your image above.
![](https://user-images.githubusercontent.com/59868086/72334574-d0526100-36bd-11ea-9748-eb937e67c0db.PNG)

I'm sorry about the fact that I won't fix that within a new v1 release due to the fact that this behaviour can be achieved with an own custom data processor. I attached you a ZIP containing a patch file and the whole updated PHP `SpreadsheetProcessor` class to be able to only show the cell selection in frontend.
[SpreadsheetProcessor.zip](https://github.com/hoogi91/spreadsheets/files/4067622/SpreadsheetProcessor.zip)

My suggestion to you is to write an own template extension (if this does not still exists) and override the `tt_content.php` like you did in the above screenshot. Then you can add the updated processor class with your own namespace inside this template extension and you only have to override the TypoScript path `tt_content.spreadsheets_table.dataProcessing.10` to the value e.g. `YourVendor\YourTemplateExtension\DataProcessing\YourSpreadsheetProcessor` and the default spreadsheet table element will use your custom data processor that only extracts the data you selected in backend ;)

With the above explained approach I was able to fix that issue very fast as you can see in the follwing screensots:
<img src="https://user-images.githubusercontent.com/13648604/72473821-c7f64500-37e7-11ea-880c-c9bf52b71788.png" width="400"/>
<img src="https://user-images.githubusercontent.com/13648604/72473876-ebb98b00-37e7-11ea-92e6-1e4a168c99f6.png" width="400"/>

I hope that this will help you at your school project to fulfill your requirements :)

<hr/>

### Information about the upcoming new version for TYPO3 v10
The new upcoming version 2 of this extension has already such support. You can find the changes in PR #11 - see:
- https://github.com/hoogi91/spreadsheets/pull/11/files#diff-f176b385d171a221bd691af495982743R83 for the change in processor to extract head and body data from the selection result of the DSN instead of the direct usage of the extraction service and...
- https://github.com/hoogi91/spreadsheets/pull/11/files#diff-00913773a8256b1b61a430a7d18ee347R88 for the change inside the DSN cell extraction that now supports/reads the range of the DSN

**Comment by RiegebMic** [comment]
Thank you very much!

**Comment by hoogi91** [comment]
fixed with #11 and will be available in next upcoming major version v2 :)
