### ISSUE TITLE
Set sheetsOnly to false as default, as stated in the documentation

### ISSUE THREAD

**Issue by Sm0ove** [hoogi91/spreadsheets#28]
**Version(s) affected**: 1.1.2

**Description**  
In the documentation, it is stated that the default value for sheetsOnly is false (https://docs.typo3.org/p/hoogi91/spreadsheets/master/en-us/Configuration/Index.html).  But in the Configuration/TCA/Overrides/tt_content.php, the value is set to true.

**How to reproduce**  
- Install version 1.1.2 of the extension
- Inspect Configuration/TCA/Overrides/tt_content.php, line 81
- The value for sheetsOnly is true

**Comment by hoogi91** [comment]
Hey @Sm0ove, that's not what the configuration was describing. As you already noticed in "Configuration/TCA/Overrides/tt_content.php" the default value has been overridden to "true". But just because this is an Override the Documentation is currently correct that it's default value is false 😄 
But I get your point that this is a bit confusing so I think the documentation should get a information block that the default content element will set this value to true because the default use case is too show a complete worksheet and not a specific selection!

**Comment by hoogi91** [comment]
Please note #41 and keep discussion on that pull request :)
