### ISSUE TITLE
No colours present on first spreadsheet on a page

### ISSUE THREAD

**Issue by mcsikos-udg** [hoogi91/spreadsheets#45]
**Version(s) affected**: 
2.0.2

**Description**  
Hi hoogie91, we have noticed an extremely strange effect here.

Attached are also a couple of screenshots to make it clearer.

When we embed a spreadsheet, it has no style information, so no colours in the front-end.

If we embed the identical one again, it will have style information.

It is always the first element that is faulty.

This is also reproducible, e.g. when we swap the elements.

Do you know what the reason could be?

**Additional context**  
![spreadsheets-01](https://user-images.githubusercontent.com/86838295/130615747-03323518-cd4b-42ce-a09e-2d53b4598a6e.png)

![spreadsheets-03](https://user-images.githubusercontent.com/86838295/130615751-fb6e564e-492c-4434-b925-8ff7e9ba1dab.png)

![spreadsheets-04](https://user-images.githubusercontent.com/86838295/130615752-ab56b0d4-9fc0-4a8a-9706-b450de69e4c4.png)

![spreadsheets-05](https://user-images.githubusercontent.com/86838295/130615754-b8c87373-a8a5-4c73-84a0-8645293d9e48.png)

**Comment by vte-udg** [comment]
I can verify that (tested V2.0.2 in a blank TYPO3 V10.4.15 with the Bootstrap-package).
It is always the first table on a page that has incorrect font and background colors (but only some, which is even stranger).

I assume the problem lies not within your code but within PhpOffice which extracts style-information from the Excel-file.
![grafik](https://user-images.githubusercontent.com/65022159/131670992-810b5195-49e6-44c0-9ab0-13186ec2a13f.png)
![grafik](https://user-images.githubusercontent.com/65022159/131671013-a97f5a66-2c70-41a0-870e-15eb632a5123.png)

**Comment by hoogi91** [comment]
Hey @vte-udg, 

I tried to reproduce the issue as described and failed :D
In my lab it works without any hassle... did you enable some specific typoscript configuration or did you had some overrides? In my opinion there could be only an existing typoscript override which prevents the first item to have it's css loaded in frontend or the PageRenderer has been modified since that class is responsible for rendering the given css of those spreadsheet files into (maybe) multiple css files.

Do you already have more debug information/input on this or is it already solved by one of the new releases?
Thanks for any new input on this :)
