### ISSUE TITLE
Fatal error after update to 2.1.0

### ISSUE THREAD

**Issue by stephangrass** [hoogi91/spreadsheets#51]
Hi,
thanks for the version 2.1.0

But after updating I get the error

Fatal error: Cannot redeclare Matrix\adjoint() (previously declared in .../typo3conf/ext/spreadsheets/Resources/Private/Composer/vendor/markbaker/matrix/classes/src/Functions/adjoint.php:21) in phar:///.../typo3conf/ext/svconnector_xls/vendors.phar/vendor/composer/../markbaker/matrix/classes/src/functions/adjoint.php on line 20

**Comment by hoogi91** [comment]
Hey @stephangrass,

I assume you are installing the extension via extension manager, right? The general problem with this extension is, that it relies on a composer based package called [phpoffice/phpspreadsheet](https://packagist.org/packages/phpoffice/phpspreadsheet). To also enable this extension to work from TER installation a small workaround has been used to include this library during deployment into TER.

The problem you faced is that the **svconnector_xls** extension also uses this extension with a similar workaround. The problem is that during initialization both extensions do not know that there is another extension using the same workaround. On your installation it seems like that the **spreadsheets** extension loads first and then includes the workaround because the classes of that composer package are not found. And a few lines later the **svconnector_xls** extension does the same and tries to redeclare some functions/classes which is not allowed in PHP world 😃 


Sad to say but this issue is not solvable in a good manner for both extension author's. I highly recommend to follow TYPO3's guideline on how to install TYPO3 in composer mode as it will simplify upgrades of all extensions and their dependencies and also allows to easily use both extensions side by side. Composer will automatically check for a version of [phpoffice/phpspreadsheet](https://packagist.org/packages/phpoffice/phpspreadsheet) that satisfies the requirements of both extensions 😃 
Please have a look at Install [TYPO3 via composer (v10)](https://docs.typo3.org/m/typo3/guide-installation/10.4/en-us/QuickInstall/Composer/Index.html) or [Install TYPO3 via composer (v11) ](https://docs.typo3.org/m/typo3/tutorial-getting-started/11.5/en-us/Installation/Install.html)
